import { afterEach, describe,it,expect,vi } from "vitest";
import { POST as create } from "../app/api/sessions/route";
import { GET as readSession } from "../app/api/sessions/[id]/route";
import { POST as lock } from "../app/api/sessions/[id]/lock/route";
import { GET as evidence } from "../app/api/sessions/[id]/evidence/route";
import { POST as interpretation } from "../app/api/sessions/[id]/interpretation/route";
import { POST as audit } from "../app/api/sessions/[id]/audit/route";
import { POST as semantic } from "../app/api/sessions/[id]/semantic/route";
import crypto from "node:crypto";
import { auditMetadataSchema, auditSchema, commitmentSchema } from "../lib/domain";
import { canonicalJson } from "../lib/record";
const commitment={claim:"The revised onboarding sequence causes more new accounts to activate.",confidence:55,rival1:"Acquisition mix changed during the experiment.",rival2:"A temporary novelty effect changed user behavior.",prediction:"Activation increases for new accounts.",refutation:"Below 10% activation lift means the claim is refuted.",design:"Randomized holdout for 14 days using activation within 7 days as the metric."};
const interpretationPacket={interpretation:"The evidence supports the onboarding claim for new accounts only.",updatedConfidence:72,proposedNextExperiment:"Run a stratified follow-up by account segment."};
const validAudit={normalizedVerdict:"aligned" as const,evidenceRelation:"supports" as const,headline:"Aligned with the prior standard",conciseRationale:"The result exceeded the prior threshold and confidence moved upward.",verdict:"partial",standardApplication:{predictionMatched:true,refutationTriggered:false,thresholdShiftedPostHoc:false,newExclusionIntroduced:false,metricChangedPostHoc:false,evidenceStandardChangedPostHoc:false},refutationStandard:{triggered:false,detail:"The observed lift is above the stated refutation threshold."},confidenceCalibration:{expectedDirection:"up",proportionate:true,detail:"Confidence increased without ignoring segment limits.",direction:"aligned" as const,magnitude:"proportionate" as const,rationale:"The update direction and size are reasonable."},interpretationQuality:{unsupportedClaims:[],detail:"The interpretation stays tied to the revealed evidence."},discrepancies:[{dimension:"confidence" as const,priorStandard:"55% initial confidence",laterPosition:"72% updated confidence",relationship:"consistent" as const,explanation:"Confidence increased after supportive evidence."}],survivingRivals:[{explanation:"Acquisition mix changed.",whyItSurvives:"Balance details are not shown.",whatWouldTestIt:"Stratify by acquisition channel."}],nextExperimentAssessment:{discriminatingPower:"medium" as const,resolves:["segment durability"],leavesOpen:["long-term novelty"],rationale:"A stratified repeat helps."},refutationStandardAnalysis:"The threshold was not triggered.",strongestNextExperiment:"Repeat with stratification for returning accounts."};
const params=(id:string)=>({params:Promise.resolve({id})});
async function session(){const r=await create();return (await r.json()).sessionId as string;}
async function markValidated(id:string){const draftHash=crypto.createHash("sha256").update(canonicalJson(commitment),"utf8").digest("hex");const { updateSession }=await import("../lib/store");await updateSession(id,x=>({...x,semanticDraftHash:draftHash,semanticStatus:"ready_to_review",commitmentLogic:{claimSubject:"onboarding",claimedOutcome:"activation",predictedObservation:"Activation increases",predictionDirection:"increase",refutationBoundary:"Below 10% activation lift",rivalExplanations:[{sourceField:"rivalExplanation1",coreMechanism:"Acquisition mix"},{sourceField:"rivalExplanation2",coreMechanism:"Novelty"}],experiment:{interventionOrComparison:"randomized holdout",measuredOutcome:"activation",durationOrStoppingRule:"14 days"}}}));}
async function interpretedSession(){const id=await session();await markValidated(id);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));await evidence(new Request("http://x"),params(id));await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify(interpretationPacket)}),params(id));return id;}
function configureOpenRouter(){process.env["OPENROUTER_API_KEY"]="test-key";process.env.OPENROUTER_MODEL="openai/gpt-5.6-sol-20260709";}
function mockOpenRouter(body:unknown,status=200){return vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));}
afterEach(()=>{delete process.env.OPENROUTER_API_KEY;delete process.env.OPENROUTER_MODEL;delete process.env.OPENROUTER_SITE_URL;delete process.env.OPENROUTER_SITE_NAME;vi.restoreAllMocks();});
describe("session integrity",()=>{
 it("new session commitment text values are empty and placeholders are not persisted",async()=>{const id=await session();const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.commitment).toBeUndefined();expect(commitmentSchema.safeParse({claim:"The revised onboarding sequence causes...",confidence:55,rival1:"An alternative explanation could be...",rival2:"Another rival explanation could be...",prediction:"If the claim is correct, I expect...",refutation:"I will treat the claim as refuted if...",design:"Describe the comparison, duration, metric, and segments..."}).success).toBe(false);});
 it("rejects whitespace-only commitment fields",async()=>{const id=await session();const r=await lock(new Request("http://x",{method:"POST",body:JSON.stringify({...commitment,claim:"     "})}),params(id));expect(r.status).toBe(400);});
 it("locks once and rejects a second lock",async()=>{const id=await session();await markValidated(id);expect((await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id))).status).toBe(200);expect((await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id))).status).toBe(409);});
 it("loads locked commitment from the server as immutable session state",async()=>{const id=await session();await markValidated(id);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.status).toBe("locked");expect(data.session.commitment.claim).toBe(commitment.claim);expect(data.session.lockedAt).toBeTruthy();});
 it("rejects evidence before lock and returns identical evidence after lock",async()=>{const a=await session();expect((await evidence(new Request("http://x"),params(a))).status).toBe(403);await markValidated(a);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(a));const one=await (await evidence(new Request("http://x"),params(a))).json();const b=await session();await markValidated(b);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(b));const two=await (await evidence(new Request("http://x"),params(b))).json();expect(one).toEqual(two);});
 it("keeps independent sessions independent",async()=>{const a=await session();const b=await session();await markValidated(a);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(a));expect((await evidence(new Request("http://x"),params(b))).status).toBe(403);});
 it("rejects weak interpretations",async()=>{const id=await session();await markValidated(id);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));await evidence(new Request("http://x"),params(id));const r=await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify({interpretation:"What does mean?",updatedConfidence:55,proposedNextExperiment:"Run another careful stratified experiment."})}),params(id));expect(r.status).toBe(400);});
 it("accepts substantive interpretation and rejects short next experiment",async()=>{const id=await session();await markValidated(id);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));await evidence(new Request("http://x"),params(id));expect((await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify({...interpretationPacket,proposedNextExperiment:"Too short"})}),params(id))).status).toBe(400);expect((await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify(interpretationPacket)}),params(id))).status).toBe(200);});
 it("semantic validation excludes evidence, persists logic, and caches exact drafts",async()=>{configureOpenRouter();const id=await session();const semanticResult={status:"ready_to_review",fields:{claim:{interpretable:true,operational:true,reason:"ok"},rivalExplanation1:{interpretable:true,distinct:true,reason:"ok"},rivalExplanation2:{interpretable:true,distinct:true,reason:"ok"},prediction:{interpretable:true,observableOutcome:true,relatedToClaim:true,reason:"ok"},refutationCondition:{interpretable:true,explicitBoundary:true,reason:"ok"},experimentDesign:{interpretable:true,comparisonOrTest:true,measuredOutcome:true,durationOrStoppingRule:true,reason:"ok"}},commitmentLogic:{claimSubject:"onboarding",claimedOutcome:"activation",predictedObservation:"Activation increases",predictionDirection:"increase",refutationBoundary:"Below 10% activation lift",rivalExplanations:[{sourceField:"rivalExplanation1",coreMechanism:"Acquisition mix"},{sourceField:"rivalExplanation2",coreMechanism:"Novelty"}],experiment:{interventionOrComparison:"randomized holdout",measuredOutcome:"activation",durationOrStoppingRule:"14 days"}}};const spy=mockOpenRouter({id:"sem_123",model:"openai/gpt-5.6-sol",usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30},choices:[{message:{content:JSON.stringify(semanticResult)}}]});const r=await semantic(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));expect(r.status).toBe(200);const payload=JSON.parse(String(spy.mock.calls[0]?.[1]?.body));expect(payload.messages[1].content).not.toContain("18% over the 14-day baseline");expect(payload.messages[1].content).not.toContain("updatedConfidence");const restored=await (await readSession(new Request("http://x"),params(id))).json();expect(restored.session.commitmentLogic.claimedOutcome).toBe("activation");const cached=await semantic(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));expect((await cached.json()).cached).toBe(true);expect(spy).toHaveBeenCalledTimes(1);}); it("requires OPENROUTER_API_KEY",async()=>{process.env.OPENROUTER_MODEL="openai/gpt-5.6-sol-20260709";const id=await interpretedSession();const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({commitment:{claim:"attacker"},evidence:{result:"fake"}})}),params(id));expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:expect.stringContaining("OPENROUTER_API_KEY")});});
 it("requires OPENROUTER_MODEL",async()=>{process.env["OPENROUTER_API_KEY"]="test-key";const id=await interpretedSession();const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:expect.stringContaining("OPENROUTER_MODEL")});});
 it("ignores browser supplied commitment and evidence",async()=>{configureOpenRouter();const id=await interpretedSession();const spy=mockOpenRouter({id:"gen_valid_123",model:"openai/gpt-5.6-sol-20260709",usage:{prompt_tokens:101,completion_tokens:202,total_tokens:303},choices:[{message:{content:JSON.stringify(validAudit)}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({commitment:{claim:"attacker override"},evidence:{result:"fake evidence"},auditMetadata:{provider:"evil",requestedModel:"fake"},normalizedVerdict:"inconsistent"})}),params(id));expect(r.status).toBe(200);const payload=JSON.parse(String(spy.mock.calls[0]?.[1]?.body));const userContent=payload.messages[1].content;expect(userContent).toContain(commitment.claim);expect(userContent).toContain("18% over the 14-day baseline");expect(userContent).not.toContain("attacker override");expect(userContent).not.toContain("fake evidence");const d=await r.json();expect(d.auditMetadata.provider).toBe("openrouter");expect(d.auditMetadata.requestedModel).toBe("openai/gpt-5.6-sol-20260709");expect(d.normalizedVerdict).toBe("aligned");});
 it("accepts valid structured OpenRouter output",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({id:"gen_valid_123",model:"openai/gpt-5.6-sol-20260709",usage:{prompt_tokens:101,completion_tokens:202,total_tokens:303},choices:[{message:{content:JSON.stringify(validAudit)}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(200);const d=await r.json();expect(auditSchema.safeParse(d).success).toBe(true);expect(auditMetadataSchema.safeParse(d.auditMetadata).success).toBe(true);expect(d.auditMetadata).toMatchObject({provider:"openrouter",requestedModel:"openai/gpt-5.6-sol-20260709",returnedModel:"openai/gpt-5.6-sol-20260709",generationId:"gen_valid_123",promptTokens:101,completionTokens:202,totalTokens:303});const restored=await (await readSession(new Request("http://x"),params(id))).json();expect(restored.session.auditMetadata).toMatchObject(d.auditMetadata);});
 it("rejects invalid structured OpenRouter output",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({choices:[{message:{content:JSON.stringify({verdict:"missing-fields"})}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(502);});
 it("provider failure produces no fake audit",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({error:"insufficient credits"},402);const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(502);expect(await r.json()).toMatchObject({error:expect.stringContaining("insufficient credits")});});
 it("validates structured audit output",()=>{expect(auditSchema.safeParse(validAudit).success).toBe(true);});
 it("rejects duplicate audit while one is pending",async()=>{const id=await interpretedSession();const { updateSession }=await import("../lib/store");await updateSession(id,x=>({...x,auditStatus:"pending"}));configureOpenRouter();const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(409);});
 it("provider 429 is recoverable and does not persist a fake audit",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({error:"rate limited"},429);const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(429);const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.audit).toBeUndefined();expect(data.session.auditStatus).toBe("failed");expect(data.session.interpretation).toBe(interpretationPacket.interpretation);});
 it("malformed provider JSON is rejected without persistence",async()=>{configureOpenRouter();const id=await interpretedSession();vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("not json",{status:200}));const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(502);const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.audit).toBeUndefined();expect(data.session.auditMetadata).toBeUndefined();expect(data.session.auditStatus).toBe("failed");});
 it("stores null usage when OpenRouter omits token usage",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({id:"gen_no_usage",model:"openai/gpt-5.6-sol-20260709",choices:[{message:{content:JSON.stringify(validAudit)}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(200);const d=await r.json();expect(d.auditMetadata.promptTokens).toBeNull();expect(d.auditMetadata.completionTokens).toBeNull();expect(d.auditMetadata.totalTokens).toBeNull();});
 it("existing completed sessions without metadata remain valid",async()=>{const id=await interpretedSession();const { updateSession }=await import("../lib/store");await updateSession(id,x=>({...x,audit:validAudit,auditStatus:"completed",status:"audited"}));const d=await (await readSession(new Request("http://x"),params(id))).json();expect(d.session.audit).toEqual(validAudit);expect(d.session.auditMetadata).toBeUndefined();});
 it("existing audits without normalized verdict remain readable",async()=>{const id=await interpretedSession();const { updateSession }=await import("../lib/store");const legacy:any={...validAudit};delete legacy.normalizedVerdict;await updateSession(id,x=>({...x,audit:legacy,auditStatus:"completed",status:"audited"}));const d=await (await readSession(new Request("http://x"),params(id))).json();expect(d.session.audit.verdict).toBe(validAudit.verdict);expect(d.session.audit.normalizedVerdict).toBeUndefined();});
 it("uses OPENROUTER_MODEL directly with no fallback model",async()=>{configureOpenRouter();const id=await interpretedSession();const spy=mockOpenRouter({id:"gen_model_source",model:"openai/gpt-5.6-sol-20260709",choices:[{message:{content:JSON.stringify(validAudit)}}]});await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));const payload=JSON.parse(String(spy.mock.calls[0]?.[1]?.body));expect(payload.model).toBe(process.env.OPENROUTER_MODEL);});});










