import { afterEach, describe,it,expect,vi } from "vitest";
import { POST as create } from "../app/api/sessions/route";
import { GET as readSession } from "../app/api/sessions/[id]/route";
import { POST as lock } from "../app/api/sessions/[id]/lock/route";
import { GET as evidence } from "../app/api/sessions/[id]/evidence/route";
import { POST as interpretation } from "../app/api/sessions/[id]/interpretation/route";
import { POST as audit } from "../app/api/sessions/[id]/audit/route";
import { auditSchema, commitmentSchema } from "../lib/domain";
const commitment={claim:"The revised onboarding sequence causes more new accounts to activate.",confidence:55,rival1:"Acquisition mix changed during the experiment.",rival2:"A temporary novelty effect changed user behavior.",prediction:"Activation increases for new accounts.",refutation:"Below 10% activation lift means the claim is refuted.",design:"Randomized holdout for 14 days using activation within 7 days as the metric."};
const interpretationPacket={interpretation:"The evidence supports the onboarding claim for new accounts only.",updatedConfidence:72,proposedNextExperiment:"Run a stratified follow-up by account segment."};
const validAudit={verdict:"partial",refutationStandard:{triggered:false,detail:"The observed lift is above the stated refutation threshold."},confidenceCalibration:{expectedDirection:"up",proportionate:true,detail:"Confidence increased without ignoring segment limits."},interpretationQuality:{unsupportedClaims:[],detail:"The interpretation stays tied to the revealed evidence."},survivingRivals:["Acquisition mix changed."],strongestNextExperiment:"Repeat with stratification for returning accounts."};
const params=(id:string)=>({params:Promise.resolve({id})});
async function session(){const r=await create();return (await r.json()).sessionId as string;}
async function interpretedSession(){const id=await session();await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));await evidence(new Request("http://x"),params(id));await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify(interpretationPacket)}),params(id));return id;}
function configureOpenRouter(){process.env["OPENROUTER_API_KEY"]="test-key";process.env.OPENROUTER_MODEL="openai/gpt-5.6-sol-20260709";}
function mockOpenRouter(body:unknown,status=200){return vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));}
afterEach(()=>{delete process.env.OPENROUTER_API_KEY;delete process.env.OPENROUTER_MODEL;delete process.env.OPENROUTER_SITE_URL;delete process.env.OPENROUTER_SITE_NAME;vi.restoreAllMocks();});
describe("session integrity",()=>{
 it("new session commitment text values are empty and placeholders are not persisted",async()=>{const id=await session();const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.commitment).toBeUndefined();expect(commitmentSchema.safeParse({claim:"The revised onboarding sequence causes...",confidence:55,rival1:"An alternative explanation could be...",rival2:"Another rival explanation could be...",prediction:"If the claim is correct, I expect...",refutation:"I will treat the claim as refuted if...",design:"Describe the comparison, duration, metric, and segments..."}).success).toBe(true);});
 it("rejects whitespace-only commitment fields",async()=>{const id=await session();const r=await lock(new Request("http://x",{method:"POST",body:JSON.stringify({...commitment,claim:"     "})}),params(id));expect(r.status).toBe(400);});
 it("locks once and rejects a second lock",async()=>{const id=await session();expect((await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id))).status).toBe(200);expect((await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id))).status).toBe(409);});
 it("loads locked commitment from the server as immutable session state",async()=>{const id=await session();await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.status).toBe("locked");expect(data.session.commitment.claim).toBe(commitment.claim);expect(data.session.lockedAt).toBeTruthy();});
 it("rejects evidence before lock and returns identical evidence after lock",async()=>{const a=await session();expect((await evidence(new Request("http://x"),params(a))).status).toBe(403);await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(a));const one=await (await evidence(new Request("http://x"),params(a))).json();const b=await session();await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(b));const two=await (await evidence(new Request("http://x"),params(b))).json();expect(one).toEqual(two);});
 it("keeps independent sessions independent",async()=>{const a=await session();const b=await session();await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(a));expect((await evidence(new Request("http://x"),params(b))).status).toBe(403);});
 it("rejects weak interpretations",async()=>{const id=await session();await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));await evidence(new Request("http://x"),params(id));const r=await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify({interpretation:"What does mean?",updatedConfidence:55,proposedNextExperiment:"Run another careful stratified experiment."})}),params(id));expect(r.status).toBe(400);});
 it("accepts substantive interpretation and rejects short next experiment",async()=>{const id=await session();await lock(new Request("http://x",{method:"POST",body:JSON.stringify(commitment)}),params(id));await evidence(new Request("http://x"),params(id));expect((await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify({...interpretationPacket,proposedNextExperiment:"Too short"})}),params(id))).status).toBe(400);expect((await interpretation(new Request("http://x",{method:"POST",body:JSON.stringify(interpretationPacket)}),params(id))).status).toBe(200);});
 it("requires OPENROUTER_API_KEY",async()=>{process.env.OPENROUTER_MODEL="openai/gpt-5.6-sol-20260709";const id=await interpretedSession();const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({commitment:{claim:"attacker"},evidence:{result:"fake"}})}),params(id));expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:expect.stringContaining("OPENROUTER_API_KEY")});});
 it("requires OPENROUTER_MODEL",async()=>{process.env["OPENROUTER_API_KEY"]="test-key";const id=await interpretedSession();const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(503);expect(await r.json()).toMatchObject({error:expect.stringContaining("OPENROUTER_MODEL")});});
 it("ignores browser supplied commitment and evidence",async()=>{configureOpenRouter();const id=await interpretedSession();const spy=mockOpenRouter({choices:[{message:{content:JSON.stringify(validAudit)}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({commitment:{claim:"attacker override"},evidence:{result:"fake evidence"}})}),params(id));expect(r.status).toBe(200);const payload=JSON.parse(String(spy.mock.calls[0]?.[1]?.body));const userContent=payload.messages[1].content;expect(userContent).toContain(commitment.claim);expect(userContent).toContain("18% over the 14-day baseline");expect(userContent).not.toContain("attacker override");expect(userContent).not.toContain("fake evidence");});
 it("accepts valid structured OpenRouter output",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({choices:[{message:{content:JSON.stringify(validAudit)}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(200);expect(auditSchema.safeParse(await r.json()).success).toBe(true);});
 it("rejects invalid structured OpenRouter output",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({choices:[{message:{content:JSON.stringify({verdict:"missing-fields"})}}]});const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(502);});
 it("provider failure produces no fake audit",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({error:"insufficient credits"},402);const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(502);expect(await r.json()).toMatchObject({error:expect.stringContaining("insufficient credits")});});
 it("validates structured audit output",()=>{expect(auditSchema.safeParse(validAudit).success).toBe(true);});
 it("rejects duplicate audit while one is pending",async()=>{const id=await interpretedSession();const { updateSession }=await import("../lib/store");await updateSession(id,x=>({...x,auditStatus:"pending"}));configureOpenRouter();const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(409);});
 it("provider 429 is recoverable and does not persist a fake audit",async()=>{configureOpenRouter();const id=await interpretedSession();mockOpenRouter({error:"rate limited"},429);const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(429);const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.audit).toBeUndefined();expect(data.session.auditStatus).toBe("failed");expect(data.session.interpretation).toBe(interpretationPacket.interpretation);});
 it("malformed provider JSON is rejected without persistence",async()=>{configureOpenRouter();const id=await interpretedSession();vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("not json",{status:200}));const r=await audit(new Request("http://x",{method:"POST",body:JSON.stringify({})}),params(id));expect(r.status).toBe(502);const data=await (await readSession(new Request("http://x"),params(id))).json();expect(data.session.audit).toBeUndefined();expect(data.session.auditStatus).toBe("failed");});});
