"use client";
import { useEffect, useState } from "react";

type Stage = "case"|"commitment"|"evidence"|"interpretation"|"audit";
type Audit = { verdict:string; refutationStandard:{triggered:boolean; detail:string}; confidenceCalibration:{expectedDirection:string; proportionate:boolean; detail:string}; interpretationQuality:{unsupportedClaims:string[]; detail:string}; survivingRivals:string[]; strongestNextExperiment:string };

export default function Home(){
 const [stage,setStage]=useState<Stage>("case"); const [locked,setLocked]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [audit,setAudit]=useState<Audit|null>(null); const [sessionId,setSessionId]=useState(""); const [evidence,setEvidence]=useState<any>(null); const [sessionError,setSessionError]=useState("");
 useEffect(()=>{let active=true; fetch("/api/sessions",{method:"POST"}).then(r=>{if(!r.ok) throw new Error("Session creation failed."); return r.json();}).then(d=>{if(active)setSessionId(d.sessionId);}).catch(()=>{if(active)setSessionError("Unable to create a session. Please reload and try again.");}); return ()=>{active=false;};},[]);
 const [form,setForm]=useState({claim:"The revised onboarding sequence causes more new accounts to activate.",confidence:55,rival1:"The lift is caused by a change in acquisition mix.",rival2:"The lift is a short-lived novelty effect.",prediction:"Activation will increase in the randomized holdout.",refutation:"If activation does not increase by at least 10% versus baseline, I will treat the claim as refuted.",design:"Randomized holdout over 14 days; compare activation within 7 days, segmented by new vs returning accounts.",interpretation:"",updated:55,next:""});
 const update=(k:string,v:string|number)=>setForm(f=>({...f,[k]:v}));
 async function lock(){if(!sessionId){setError(sessionError||"Session is not ready.");return;}setError(""); setLoading(true); const r=await fetch(`/api/sessions/${sessionId}/lock`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json(); setLoading(false); if(!r.ok){setError(d.error);return;} setLocked(true);setStage("evidence");}
 async function reveal(){const r=await fetch(`/api/sessions/${sessionId}/evidence`);const d=await r.json();if(!r.ok){setError(d.error);return;}setEvidence(d);setStage("interpretation");}
 async function runAudit(){setError("");setLoading(true);const i=await fetch(`/api/sessions/${sessionId}/interpretation`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({interpretation:form.interpretation,updatedConfidence:form.updated,proposedNextExperiment:form.next})});if(!i.ok){const d=await i.json();setError(d.error);setLoading(false);return;}const r=await fetch(`/api/sessions/${sessionId}/audit`,{method:"POST"});const d=await r.json();setLoading(false);if(!r.ok){setError(d.error);return;}setAudit(d);setStage("audit");}
 const stageIndex=["case","commitment","evidence","interpretation","audit"].indexOf(stage);
 return <main><header><div className="wordmark"><span className="mark">BE</span><span>BEFORE EVIDENCE</span></div><div className="registry">REGISTRY 01 <span className="dot"></span> {locked?"SEALED":"OPEN"}</div></header>
 <section className="hero"><div className="eyebrow">AN EPISTEMIC REGISTRY</div><h1>Decide what<br/><em>would change</em><br/>your mind.</h1><p className="lede">Before Evidence asks you to register your standard before the evidence arrives. Your future interpretation is examined against the record.</p></section>
 <nav className="steps">{["CASE","COMMITMENT","REVEAL","INTERPRET","AUDIT"].map((s,i)=><div className={i<=stageIndex?"active":""} key={s}><b>0{i+1}</b><span>{s}</span></div>)}</nav>
 <section className="workspace">{sessionError&&<div className="error">{sessionError}</div>}
 {stage==="case"&&<div className="sheet"><div className="sheet-label">CASE FILE / 001</div><h2>Does revised onboarding cause more activation?</h2><p>One excellent question. A fixed experiment. A standard registered before the result can affect you.</p><div className="scenario"><span className="seal">01</span><div><strong>THE ONBOARDING EFFECT</strong><small>New account activation  randomized holdout  14 days</small></div></div><button className="button" onClick={()=>setStage("commitment")}>Open the commitment record <span></span></button></div>}
 {stage==="commitment"&&<div className="sheet"><div className="sheet-label">COMMITMENT / PRE-REGISTRATION</div><h2>Write the standard<br/><em>before the result.</em></h2><p className="instruction">Every field becomes part of the sealed record. Precision here is the point.</p><Field label="CLAIM" value={form.claim} onChange={v=>update("claim",v)} /><div className="two"><Field label="INITIAL CONFIDENCE" value={String(form.confidence)+"%"} type="range" onChange={v=>update("confidence",Number(v))} /><div className="confidence">{form.confidence}%<small>prior belief</small></div></div><Field label="RIVAL EXPLANATION 01" value={form.rival1} onChange={v=>update("rival1",v)} /><Field label="RIVAL EXPLANATION 02" value={form.rival2} onChange={v=>update("rival2",v)} /><Field label="PREDICTION" value={form.prediction} onChange={v=>update("prediction",v)} /><div className="refute"><label>REFUTATION CONDITION</label><textarea value={form.refutation} onChange={e=>update("refutation",e.target.value)}/><small>The observable result that would force a meaningful update.</small></div><Field label="EXPERIMENT DESIGN" value={form.design} onChange={v=>update("design",v)} /><div className="lockline"><span></span><p>Once sealed, this record cannot be edited  by you or by the interface.</p><button className="button" onClick={lock} disabled={loading}>{loading?"Sealing":"Seal the standard  "}</button></div>{error&&<div className="error">{error}</div>}</div>}
 {stage==="evidence"&&<div className="sheet reveal"><div className="sheet-label">EVIDENCE / PREDETERMINED RESULT</div><div className="reveal-icon"></div><h2>The record is sealed.<br/><em>Now see what happened.</em></h2><p>Your standard was registered. The evidence remains server-held until this reveal transition.</p><button className="button" onClick={reveal}>Reveal the evidence  </button></div>}
 {stage==="interpretation"&&<div className="sheet"><div className="sheet-label">INTERPRETATION / POST-EVIDENCE</div><h2>What do you<br/><em>conclude?</em></h2><p className="instruction">The evidence is visible. Give your reading, then update the belief you registered.</p><div className="evidence mini"><div><label>OBSERVED</label><strong>RESULT</strong><span>new-account activation</span></div><div><label>YOUR STANDARD</label><p>The registered refutation standard</p></div></div><Field label="YOUR INTERPRETATION" value={form.interpretation} onChange={v=>update("interpretation",v)} placeholder="What does this result mean? What does it not mean?" textarea /><div className="two"><Field label="UPDATED CONFIDENCE" value={String(form.updated)+"%"} type="range" onChange={v=>update("updated",Number(v))}/><div className="confidence">{form.updated}%<small>posterior belief</small></div></div><Field label="PROPOSED NEXT EXPERIMENT" value={form.next} onChange={v=>update("next",v)} placeholder="What would discriminate between the remaining explanations?" textarea /><button className="button" onClick={runAudit} disabled={loading}>{loading?"Examining the record":"Submit for audit  "}</button>{error&&<div className="error">{error}</div>}</div>}
 {stage==="audit"&&audit&&<AuditView audit={audit} form={form} evidence={evidence} />}
 </section><footer><span>BEFORE EVIDENCE / BUILD WEEK 2026</span><span>SCENARIO 2026.07.20-A</span></footer></main>
}
function Field({label,value,onChange,type="text",placeholder,textarea}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string;textarea?:boolean}){return <div className="field"><label>{label}</label>{textarea?<textarea value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} />}</div>}
function AuditView({audit,form,evidence}:{audit:Audit;form:any;evidence:any}){return <div className="audit"><div className="sheet-label">AUDIT / GPT-5.6 EPISTEMIC REVIEW</div><h2>The record, <em>examined.</em></h2><p className="instruction">A structured audit of what you said, what happened, and what you concluded.</p><div className="audit-grid"><div><label>WHAT YOU SAID</label><p>{form.claim}</p><span>{form.confidence}% initial confidence</span></div><div><label>WHAT HAPPENED</label><p>{evidence.result}</p><span>Evidence version 2026.07.20-A</span></div><div><label>WHAT YOU CONCLUDED</label><p>{form.interpretation||"No interpretation supplied."}</p><span>{form.updated}% updated confidence</span></div></div><div className="verdict"><label>VERDICT</label><strong>{audit.verdict}</strong><p>{audit.interpretationQuality.detail}</p></div><div className="audit-sections"><AuditSection title="01 / REFUTATION STANDARD" body={audit.refutationStandard.detail} tag={audit.refutationStandard.triggered?"TRIGGERED":"NOT TRIGGERED"}/><AuditSection title="02 / CONFIDENCE CALIBRATION" body={audit.confidenceCalibration.detail} tag={audit.confidenceCalibration.proportionate?"PROPORTIONATE":"EXAMINE MAGNITUDE"}/><AuditSection title="03 / SURVIVING RIVALS" body={audit.survivingRivals.join(" ")} /><AuditSection title="04 / STRONGEST NEXT EXPERIMENT" body={audit.strongestNextExperiment}/></div></div>}
function AuditSection({title,body,tag}:{title:string;body:string;tag?:string}){return <div className="audit-section"><label>{title}</label>{tag&&<b>{tag}</b>}<p>{body}</p></div>}
