import type { Commitment } from "./domain";

export const emptyCommitment:Commitment={claim:"",confidence:55,rival1:"",rival2:"",prediction:"",refutation:"",design:""};
export const commitmentPlaceholders={claim:"The revised onboarding sequence causes...",rival1:"An alternative explanation could be...",rival2:"Another rival explanation could be...",prediction:"If the claim is correct, I expect...",refutation:"I will treat the claim as refuted if...",design:"Describe the comparison, duration, metric, and segments..."};
export const commitmentRules={claim:{min:20,message:"Enter a claim of at least 20 characters."},rival1:{min:15,message:"Enter a rival explanation of at least 15 characters."},rival2:{min:15,message:"Enter a second rival explanation of at least 15 characters."},prediction:{min:15,message:"Enter a prediction of at least 15 characters."},refutation:{min:20,message:"Enter a refutation condition of at least 20 characters."},design:{min:25,message:"Enter an experiment design of at least 25 characters."}} as const;
export function validateCommitmentDraft(value:Commitment){const errors:Record<string,string>={};for(const [key,rule] of Object.entries(commitmentRules)){const text=String(value[key as keyof Commitment]||"").trim();if(text.length<rule.min)errors[key]=rule.message;}return errors;}
export function canEnterReview(value:Commitment){return Object.keys(validateCommitmentDraft(value)).length===0;}
export function cancelSeal(status:"open"|"locked"){return {status,lockCalled:false};}
export function confirmSeal(status:"open"|"locked"){return {status,lockCalled:status==="open"};}
export function isPostLockReadOnly(status:string){return status!=="open";}
export function validateInterpretationDraft(interpretation:string,nextExperiment:string){const errors:Record<string,string>={};const text=interpretation.trim();if(text.length<40)errors.interpretation="Write at least 40 characters about what the evidence implies.";else if(/^\s*[^.!]*\?\s*$/.test(text))errors.interpretation="The interpretation cannot be only a question.";else if(!/\b(implies|suggests|shows|means|supports|indicates|demonstrates)\b/i.test(text))errors.interpretation="State what the evidence implies.";if(nextExperiment.trim().length<25)errors.next="Enter a next experiment of at least 25 characters.";return errors;}