import type { Commitment } from "./domain";

export type QualityResult={valid:boolean;wordCount:number;alphabeticRatio:number;reasons:string[]};
const latinWord=/[\p{Script=Latin}][\p{Script=Latin}'\u2019-]*/gu;
const relationalVerb=/\b(caus(?:e|es|ed|ing)|increas\w*|decreas\w*|reduc\w*|improv\w*|rais\w*|lower\w*|predict\w*|lead\w*|chang\w*|affect\w*|support\w*|correlat\w*|drive\w*|boost\w*|hurt\w*|higher|lower|more|less|augmente\w*|reduit|reduis\w*|reduit\w*|ameliore\w*|diminu\w*)\b/i;
const outcomeSignal=/\b(activation|completion|conversion|checkout|latency|retention|revenue|lift|rate|score|outcome|result|success|failure|day-?\d+|jour|compte|accounts?|cohorts?|users?|clients?)\b/i;
function words(text:string){return Array.from(text.matchAll(latinWord)).map(m=>m[0]).filter(w=>/[\p{L}]/u.test(w));}
function symbolRatio(text:string){const compact=text.replace(/\s/g,"");if(!compact)return 1;const symbols=Array.from(compact).filter(ch=>!/[\p{L}\p{N}%.'\u2019_-]/u.test(ch)).length;return symbols/compact.length;}
function lexicalDiversity(ws:string[]){if(!ws.length)return 0;return new Set(ws.map(w=>w.toLowerCase())).size/ws.length;}
function repeatedChars(text:string){return /(.)\1{5,}/u.test(text);}
function keyboardLike(text:string){return /(?:qwerty|asdf|zxcv|hjkl|azerty|qsdf|gvdch|jkl|poiuy|lkj|uiop)/i.test(text)||/[bcdfghjklmnpqrstvwxyz]{10,}/i.test(text.replace(/\s/g,""));}
function repeatedTokens(ws:string[]){const lower=ws.map(w=>w.toLowerCase());return lower.some((w,i)=>w.length>2&&lower[i+1]===w&&lower[i+2]===w);}
function lowWhitespace(text:string,ws:string[]){return text.length>35&&ws.length<4&&text.trim().split(/\s+/).length<3;}
export function quality(text:string,minWords=4):QualityResult{const trimmed=text.trim();const chars=Array.from(trimmed);const alpha=chars.filter(c=>/[\p{L}]/u.test(c)).length;const ws=words(trimmed);const reasons:string[]=[];const alphabeticRatio=chars.length?alpha/chars.length:0;if(ws.length<minWords)reasons.push("too_few_words");if(alphabeticRatio<0.45)reasons.push("mostly_non_language");if(symbolRatio(trimmed)>0.22)reasons.push("symbol_heavy");if(lowWhitespace(trimmed,ws))reasons.push("little_whitespace");if(keyboardLike(trimmed))reasons.push("keyboard_like");if(repeatedChars(trimmed)||repeatedTokens(ws))reasons.push("repetition");if(ws.length>=5&&lexicalDiversity(ws)<0.55)reasons.push("low_diversity");if(/[.!?;:,]{4,}/.test(trimmed))reasons.push("punctuation_padding");return {valid:reasons.length===0,wordCount:ws.length,alphabeticRatio,reasons};}
export function userQualityMessage(result:QualityResult){if(result.reasons.includes("keyboard_like")||result.reasons.includes("mostly_non_language"))return "This text appears to contain random or non-interpretable characters.";if(result.reasons.includes("too_few_words"))return "This field needs a clearer natural-language statement.";if(result.reasons.includes("symbol_heavy")||result.reasons.includes("punctuation_padding"))return "This field needs meaningful words rather than punctuation or symbols.";if(result.reasons.includes("little_whitespace")||result.reasons.includes("repetition")||result.reasons.includes("low_diversity"))return "This field appears repetitive or not yet understandable.";return "This field is not yet understandable.";}
function hasAny(text:string,patterns:RegExp[]){return patterns.some(p=>p.test(text));}
function hasOperationalClaimStructure(text:string){const matches=Array.from(text.matchAll(new RegExp(relationalVerb.source,"gi")));for(const match of matches){if(match.index===undefined)continue;const before=words(text.slice(0,match.index));const afterText=text.slice(match.index+match[0].length);const after=words(afterText);if(before.length>=1&&after.length>=2&&outcomeSignal.test(afterText))return true;}return false;}
export function validateOperationalCommitment(c:Commitment){const errors:Record<string,string>={};const fields:[keyof Commitment,number][]=[["claim",5],["rival1",4],["rival2",4],["prediction",4],["refutation",4],["design",6]];for(const [key,min] of fields){const r=quality(String(c[key]),min);if(!r.valid)errors[key]=userQualityMessage(r);}const claim=c.claim.toLowerCase(),r1=c.rival1.toLowerCase(),r2=c.rival2.toLowerCase();if(!errors.claim&&!hasOperationalClaimStructure(c.claim))errors.claim="This claim is not yet understandable as a complete statement.";if(!errors.prediction&&!hasAny(c.prediction,[/\b(increas\w*|decreas\w*|higher|lower|more|less|above|below|change|no change|activat\w*|conversion|lift|rise|fall|augment\w*|diminu\w*|superieur|inferieur)\b/i]))errors.prediction="This prediction needs an observable expected result.";if(!errors.refutation&&!hasAny(c.refutation,[/\b(below|above|less than|more than|under|over|fail|no\s+change|zero|not|without|if|unless|moins|plus|echec|aucun)\b/i,/\d/]))errors.refutation="This refutation condition does not yet identify what outcome would count against the claim.";if(!errors.design){const hasTest=hasAny(c.design,[/\b(random|holdout|compare|comparison|test|experiment|measure|observe|control|variant|cohort|ab\b|a\/b|essai|mesur\w*|compar\w*)\b/i]);const hasWindow=hasAny(c.design,[/\b\d+\s*(day|days|week|weeks|month|months|jour|jours|semaine|semaines|mois)\b/i,/\buntil|before|after|pendant|durant\b/i]);if(!hasTest||!hasWindow)errors.design="This experiment needs a comparison, measured outcome, and observation window.";}const overlap=(a:string,b:string)=>{const aw=new Set(words(a).map(w=>w.toLowerCase()).filter(w=>w.length>3));const bw=words(b).map(w=>w.toLowerCase()).filter(w=>w.length>3);if(!aw.size||!bw.length)return 0;return bw.filter(w=>aw.has(w)).length/Math.max(aw.size,bw.length);};if(!errors.rival2&&(r1===r2||overlap(r1,r2)>0.72))errors.rival2="These rival explanations are too similar.";if(!errors.rival1&&overlap(claim,r1)>0.78)errors.rival1="This rival explanation is too similar to the claim.";if(!errors.rival2&&overlap(claim,r2)>0.78)errors.rival2="This rival explanation is too similar to the claim.";return errors;}
export function validateOperationalInterpretation(interpretation:string,nextExperiment:string){const errors:Record<string,string>={};const i=quality(interpretation,6);if(!i.valid)errors.interpretation=userQualityMessage(i);if(!errors.interpretation&&!/\b(implies|suggests|shows|means|supports|indicates|demonstrates|does not|ne montre pas|suggere|indique)\b/i.test(interpretation))errors.interpretation="State what the evidence implies and what it does not establish.";const n=quality(nextExperiment,6);if(!n.valid)errors.next=userQualityMessage(n);if(!errors.next&&!/\b(test|compare|measure|observe|repeat|random|holdout|experiment|cohort|segment|run|follow|mesur|compar|tester)\b/i.test(nextExperiment))errors.next="The next experiment needs a real test, comparison, or measured observation.";return errors;}