import type { Audit, AuditMetadata, Commitment, Session } from "./domain";

export const recordSchemaVersion="before-evidence-record-1";
export const exportVersion="before-evidence-export-1";
export type CanonicalSealedRecord={schemaVersion:string;caseId:string;scenarioId:string;claim:string;rivalExplanations:[string,string];prediction:string;refutationCondition:string;experimentDesign:string;initialConfidence:number;sealedAt:string};
export type VerificationResult="match"|"mismatch"|"invalid_format";

function stable(value:unknown):unknown{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object"){const out:Record<string,unknown>={};for(const key of Object.keys(value as Record<string,unknown>).sort())out[key]=stable((value as Record<string,unknown>)[key]);return out;}return value;}
export function canonicalJson(value:unknown){return JSON.stringify(stable(value));}
export function canonicalCommitmentRecord(args:{caseId:string;scenarioId:string;commitment:Commitment;sealedAt:string}):CanonicalSealedRecord{return {schemaVersion:recordSchemaVersion,caseId:args.caseId,scenarioId:args.scenarioId,claim:args.commitment.claim.trim(),rivalExplanations:[args.commitment.rival1.trim(),args.commitment.rival2.trim()],prediction:args.commitment.prediction.trim(),refutationCondition:args.commitment.refutation.trim(),experimentDesign:args.commitment.design.trim(),initialConfidence:args.commitment.confidence,sealedAt:args.sealedAt};}
export function canonicalSealedString(record:CanonicalSealedRecord){return canonicalJson(record);}
export function normalizeFingerprint(value:string){return value.startsWith("sha256:")?value:`sha256:${value}`;}
export function shortFingerprint(value?:string){if(!value)return "Fingerprint unavailable for legacy record.";const raw=value.replace(/^sha256:/,"");return `sha256: ${raw.slice(0,8)}...${raw.slice(-8)}`;}
export function formatEnumLabel(value?:string){if(!value)return "UNAVAILABLE";return value.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/[_-]+/g," ").trim().replace(/\s+/g," ").toUpperCase()||"UNAVAILABLE";}
export function formatDimensionLabel(value?:string){return formatEnumLabel(value);}
export function formatRelationshipLabel(value?:string){return formatEnumLabel(value);}
export function normalizedVerdictLabel(value?:Audit["normalizedVerdict"]){return value?formatEnumLabel(value):"LEGACY AUDIT";}
export function preSealChecks(c:Commitment){const text=`${c.refutation} ${c.design} ${c.prediction}`;const threshold=/\b\d+(\.\d+)?\s*(%|percent\b|points?\b)/i.test(text);const duration=/\b\d+\s*(day|days|week|weeks|month|months)\b/i.test(text);const a=c.rival1.trim().toLowerCase();const b=c.rival2.trim().toLowerCase();const similar=!!a&&!!b&&(a===b||a.includes(b)||b.includes(a));return [{id:"threshold",label:"Numeric threshold",status:threshold?"ready":"review",detail:threshold?"A numeric decision boundary is present.":"Consider naming the numeric boundary that would change your mind."},{id:"duration",label:"Duration",status:duration?"ready":"review",detail:duration?"A time window is present.":"Consider naming the observation window."},{id:"rivals",label:"Rival distinction",status:similar?"review":"ready",detail:similar?"The rival explanations look very similar.":"The rival explanations are distinguishable."}] as const;}
export function buildExport(session:Session,evidence:unknown){if(!session.commitment||!session.lockedAt)return undefined;const canonical=canonicalCommitmentRecord({caseId:"case-001",scenarioId:session.scenarioId,commitment:session.commitment,sealedAt:session.lockedAt});const confidenceDelta=session.updatedConfidence!==undefined?session.updatedConfidence-session.commitment.confidence:undefined;return {exportVersion,recordSchemaVersion:session.recordSchemaVersion??recordSchemaVersion,caseId:"case-001",scenarioId:session.scenarioId,sessionId:session.sessionId,canonicalSealedCommitment:canonical,recordFingerprint:session.recordFingerprint,sealedAt:session.lockedAt,evidenceVersion:session.evidenceRevealedAt?session.evidenceVersion:undefined,evidence:session.evidenceRevealedAt?evidence:undefined,interpretation:session.interpretation,updatedConfidence:session.updatedConfidence,confidenceDelta,proposedNextExperiment:session.proposedNextExperiment,normalizedVerdict:session.audit?.normalizedVerdict,auditHeadline:session.audit?.verdict,auditRationale:session.audit?.interpretationQuality.detail,audit:session.audit,auditMetadata:session.auditMetadata,exportedAt:new Date().toISOString(),integrityLimitations:"This fingerprint verifies only that the exported commitment matches the sealed commitment for this session. It does not prove identity, legal validity, blockchain registration, or independent third-party timestamping."};}
export function markdownExport(record:ReturnType<typeof buildExport>){if(!record)return "";const audit=record.audit;return [`# BEFORE EVIDENCE`,``,`## Case`,`Scenario: ${record.scenarioId}`,``,`## Sealed Commitment`,`Claim: ${record.canonicalSealedCommitment.claim}`,`Initial confidence: ${record.canonicalSealedCommitment.initialConfidence}%`,`Prediction: ${record.canonicalSealedCommitment.prediction}`,`Refutation condition: ${record.canonicalSealedCommitment.refutationCondition}`,`Experiment design: ${record.canonicalSealedCommitment.experimentDesign}`,`Rivals: ${record.canonicalSealedCommitment.rivalExplanations.join("; ")}`,``,`## Record Fingerprint`,record.recordFingerprint||"Fingerprint unavailable for legacy record.",``,`## Predetermined Evidence`,record.evidence?JSON.stringify(record.evidence,null,2):"Not revealed in this export.",``,`## User Interpretation`,record.interpretation||"Not submitted.",``,`## Confidence Update`,record.updatedConfidence!==undefined?`${record.updatedConfidence}% (${record.confidenceDelta!>=0?"+":""}${record.confidenceDelta} points)`:"Not submitted.",``,`## Normalized Verdict`,record.normalizedVerdict?normalizedVerdictLabel(record.normalizedVerdict):"Not audited.",``,`## GPT Audit`,audit?`${audit.verdict}\n\nRefutation standard: ${audit.refutationStandard.detail}\n\nConfidence calibration: ${audit.confidenceCalibration.detail}\n\nSurviving rivals: ${audit.survivingRivals.join("; ")}\n\nStrongest next experiment: ${audit.strongestNextExperiment}`:"Not audited.",``,`## Audit Metadata`,record.auditMetadata?JSON.stringify(record.auditMetadata,null,2):"Not available.",``,`## Integrity Limitations`,record.integrityLimitations].join("\n");}
export function parseExport(text:string){try{const data=JSON.parse(text);if(data?.exportVersion!==exportVersion||data?.recordSchemaVersion!==recordSchemaVersion||!data?.canonicalSealedCommitment)return undefined;return data as NonNullable<ReturnType<typeof buildExport>>;}catch{return undefined;}}
export function compareVerification(calculated:string,expected?:string){if(!expected)return "invalid_format" as const;return normalizeFingerprint(calculated)===normalizeFingerprint(expected)?"match":"mismatch";}

